#! /bin/sh

#Autostart
pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch.sh &
xcompmgr -c & ##start compositer
feh --bg-center $HOME/img/wall/paper
#feh --bg-center $HOME/img/wall/paper --bg-center $HOME/img/wall/paper2 & ##set wallpaper with feh
#feh --bg-fill $HOME/img/wall/lateralis.JPG &
#$HOME/.config/bspwm/reordermon.sh &
discord &
skype &
emacs --daemon &
xscreensaver -no-splash &
xsetroot -cursor_name left_ptr & ##setting the initial mouse pointer status. still needed?

bspc wm --reorder-monitors DVI-0 DVI-1
bspc monitor DVI-0 -d 1 2 3 4 5
bspc monitor DVI-1 -d 6 7 8 9 0

#Visual Elements
bspc config border_width         2
bspc config window_gap          5
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config ignore_ewmh_focus true
bspc config focused_border_color "#ff79c6"
bspc config normal_border_color "#44475a"
bspc config active_border_color "#bd93f9"
bspc config presel_feedback_color "#6272a4"

#node rules and geometry
#
#dropdownname="dropdown"
#bspc query -N -n .hidden >/dev/null || setsid $TERMINAL -n "$dropdownname" -e dropdown >/dev/null 2>&1 &
#bspc rule -a St:$dropdownname hidden=on
#bspc rule -a St:$dropdownname sticky=on
#bspc rule -a St:$dropdownname state=floating
#
#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
#bspc rule -a Pavucontrol state=floating
bspc rule -a Emacs state=tiled focus=on
bspc rule -a mpv state=tiled focus=on
bspc rule -a discord desktop='^10' state=tiled focus=on
bspc rule -a Skype desktop='^10' state=tiled
